###
POST http://readstack-backend.herokuapp.com/register/ 
content-type: application/json

{
  "username": "user2", 
  "email": "user2@gmail.com", 
  "password": "123"
}

###
POST http://readstack-backend.herokuapp.com/login/ 
content-type: application/json

{
  "username": "authTest",  
  "password": "123"
}




###
POST http://readstack-backend.herokuapp.com/stacks/ 
content-type: application/json
Authorization: 2

{
  "name": "Software Engineering"
}


###
POST http://readstack-backend.herokuapp.com/books/ 
content-type: application/json
Authorization: 2

{
  "title": "ecks",
  "author": "dee", 
  "stack_id": 2, 
  "cover_photo_url": "https://external-preview.redd.it/x3W_tPGBToPGjhcrWquMJiDxXFwsTX3yCeAqomZkjxY.png?auto=webp&s=c2fcff59adb0d468306e4fb6367fa387a455186e"
}


###
GET http://readstack-backend.herokuapp.com/users

###
GET http://readstack-backend.herokuapp.com/stacks/?username=user1


###
GET http://readstack-backend.herokuapp.com/books



###
PUT http://readstack-backend.herokuapp.com/users/4
content-type: application/json
Authorization: 4

{
  "old_password": "123", 
  "new_password": "1234"
}



###
DELETE http://readstack-backend.herokuapp.com/users/1


###
DELETE http://readstack-backend.herokuapp.com/stacks/2
Authorization: 2


###
DELETE http://readstack-backend.herokuapp.com/books/2
Authorization: 2
